export enum OdfAttributeName {
  FormatBackgroundColor = 'fo:background-color',
  FormatBorderBottom = 'fo:border-bottom',
  FormatBorderLeft = 'fo:border-left',
  FormatBorderRight = 'fo:border-right',
  FormatBorderTop = 'fo:border-top',
  FormatBreakAfter = 'fo:break-after',
  FormatBreakBefore = 'fo:break-before',
  FormatColor = 'fo:color',
  FormatFontSize = 'fo:font-size',
  FormatFontStyle = 'fo:font-style',
  FormatFontVariant = 'fo:font-variant',
  FormatFontWeight = 'fo:font-weight',
  FormatKeepTogether = 'fo:keep-together',
  FormatKeepWithNext = 'fo:keep-with-next',
  FormatLineHeight = 'fo:line-height',
  FormatMarginBottom = 'fo:margin-bottom',
  FormatMarginLeft = 'fo:margin-left',
  FormatMarginRight = 'fo:margin-right',
  FormatMarginTop = 'fo:margin-top',
  FormatOrphans = 'fo:orphans',
  FormatPaddingBottom = 'fo:padding-bottom',
  FormatPaddingLeft = 'fo:padding-left',
  FormatPaddingRight = 'fo:padding-right',
  FormatPaddingTop = 'fo:padding-top',
  FormatTextAlign = 'fo:text-align',
  FormatTextAlignLast = 'fo:text-align-last',
  FormatTextIndent = 'fo:text-indent',
  FormatTextTransform = 'fo:text-transform',
  FormatWidows = 'fo:widows',

  OfficeMimetype = 'office:mimetype',
  OfficeVersion = 'office:version',

  StyleChar = 'style:char',
  StyleFamily = 'style:family',
  StyleFontName = 'style:font-name',
  StyleLeaderColor = 'style:leader-color',
  StyleLeaderStyle = 'style:leader-style',
  StyleLineHeightAtLeast = 'style:line-height-at-least',
  StyleLineSpacing = 'style:line-spacing',
  StyleName = 'style:name',
  StylePosition = 'style:position',
  StyleType = 'style:type',
  StyleVerticalAlign = 'style:vertical-align',

  SvgHeight = 'svg:height',
  SvgWidth = 'svg:width',

  TextAnchorType = 'text:anchor-type',
  TextConsecutiveNumbering = 'text:consecutive-numbering',
  TextLevel = 'text:level',
  TextOutlineLevel = 'text:outline-level',
  TextStyleName = 'text:style-name',

  XlinkHref = 'xlink:href',
  XlinkType = 'xlink:type',
}
